import { useState, useCallback } from 'react';
import { Chat, Message, DocumentSource } from '@/types';

// Mock data for demo purposes
const mockChats: Chat[] = [
  {
    id: '1',
    title: 'Understanding RAG Architecture',
    messages: [
      {
        id: 'm1',
        role: 'user',
        content: 'How does RAG work?',
        timestamp: new Date(Date.now() - 3600000),
      },
      {
        id: 'm2',
        role: 'assistant',
        content: 'RAG (Retrieval-Augmented Generation) combines document retrieval with language model generation. When you ask a question, the system first searches your documents for relevant chunks, then uses those chunks as context for the AI to generate an accurate response.',
        timestamp: new Date(Date.now() - 3500000),
        sources: [
          { documentId: 'd1', documentName: 'rag-overview.pdf', chunk: 'RAG combines retrieval and generation...', relevance: 0.95 },
        ],
      },
    ],
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 3500000),
  },
  {
    id: '2',
    title: 'Vector Embeddings Explained',
    messages: [],
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 172800000),
  },
  {
    id: '3',
    title: 'Chunking Strategies',
    messages: [],
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(Date.now() - 259200000),
  },
];

// TODO: Replace with actual backend API calls
export function useChat() {
  const [chats, setChats] = useState<Chat[]>(mockChats);
  const [activeChatId, setActiveChatId] = useState<string | null>('1');
  const [isLoading, setIsLoading] = useState(false);

  const activeChat = chats.find(c => c.id === activeChatId) || null;

  const createChat = useCallback(() => {
    const newChat: Chat = {
      id: `chat-${Date.now()}`,
      title: 'New Conversation',
      messages: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };
    setChats(prev => [newChat, ...prev]);
    setActiveChatId(newChat.id);
    return newChat;
  }, []);

  const deleteChat = useCallback((chatId: string) => {
    setChats(prev => prev.filter(c => c.id !== chatId));
    if (activeChatId === chatId) {
      setActiveChatId(null);
    }
  }, [activeChatId]);

  const sendMessage = useCallback(async (content: string) => {
    if (!activeChatId) return;

    const userMessage: Message = {
      id: `msg-${Date.now()}`,
      role: 'user',
      content,
      timestamp: new Date(),
    };

    setChats(prev => prev.map(chat => {
      if (chat.id === activeChatId) {
        const newTitle = chat.messages.length === 0 
          ? content.slice(0, 30) + (content.length > 30 ? '...' : '')
          : chat.title;
        return {
          ...chat,
          title: newTitle,
          messages: [...chat.messages, userMessage],
          updatedAt: new Date(),
        };
      }
      return chat;
    }));

    setIsLoading(true);

    // TODO: Replace with actual AI backend call
    await new Promise(resolve => setTimeout(resolve, 1500));

    const mockSources: DocumentSource[] = [
      { documentId: 'd1', documentName: 'knowledge-base.pdf', chunk: 'Relevant context from your documents...', relevance: 0.92 },
      { documentId: 'd2', documentName: 'notes.md', chunk: 'Additional supporting information...', relevance: 0.85 },
    ];

    const assistantMessage: Message = {
      id: `msg-${Date.now() + 1}`,
      role: 'assistant',
      content: `Based on your documents, here's what I found regarding "${content}":\n\nThis is a mock response. In a real implementation, this would be generated by your AI model using RAG to retrieve relevant context from your indexed documents.`,
      timestamp: new Date(),
      sources: mockSources,
    };

    setChats(prev => prev.map(chat => {
      if (chat.id === activeChatId) {
        return {
          ...chat,
          messages: [...chat.messages, assistantMessage],
          updatedAt: new Date(),
        };
      }
      return chat;
    }));

    setIsLoading(false);
  }, [activeChatId]);

  return {
    chats,
    activeChat,
    activeChatId,
    setActiveChatId,
    createChat,
    deleteChat,
    sendMessage,
    isLoading,
  };
}
